### PR TITLE
Feature/rm blist

### PR DESCRIPTION
**Pull request by Richard-Mathie**

### CODE REVIEW

**Comment by Richard-Mathie** [comment]
Also would it be possible for you to consider adding travis automatic deployment, see:
https://docs.travis-ci.com/user/deployment/pypi/

you will need to
```
travis setup pypi
travis encrypt --add deploy.password
```

so that we have this in .travis.yml
```
deploy:
  provider: pypi
  user: "Your username"
  password:
    secure: "Your encrypted password"
  on:
    tags: true
  distributions: "sdist bdist_wheel"
```

**Comment by thegeorgeous** [comment]
@Richard-Mathie, the ideas sounds good in theory. I'll have to look into it though. Also can you give me permissions to edit this PR
https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by thegeorgeous** [comment]
@Richard-Mathie do you mind if I add you as a collaborator for this project? I no longer actively use this plugin and making regular updates is difficult for me.

**Comment by Richard-Mathie** [comment]
Yeah that would be fine

all the best

**Comment by Richard-Mathie** [comment]
it is already enabled by default?
image

**Comment by Richard-Mathie** [comment]
also my pypi username is RichardMathie if that helps

you can add me as a maintainer if you want and I can run through the travis stuff.

**Comment by thegeorgeous** [comment]
@Richard-Mathie, looks like tests are failing.

**Comment by Richard-Mathie** [comment]
1 Travis build out of 70 failed #94.51  Python: pypy3 CASSANDRA_DRIVER_VERSION=2.6.0 
```
------------------------------- Captured stderr --------------------------------
/home/travis/build/thegeorgeous/flask-cqlalchemy/tests/test_cqlalchemy.py:4: ExtDeprecationWarning: Importing flask.ext.cqlalchemy is deprecated, use flask_cqlalchemy instead.
  from flask.ext.cqlalchemy import CQLAlchemy
__________________ ERROR collecting tests/test_cqlalchemy.py ___________________
```

will update the test file

**Comment by Richard-Mathie** [comment]
Build now passing,

cassandra driver 2.6 dosnt work with pypy3 but that is their concern, also Its quite an old driver.

Looks like i don't have writes to review or close out pull requests

**Comment by thegeorgeous** [comment]
@Richard-Mathie, thanks! I'll review and merge it tomorrow.

**Review by thegeorgeous — APPROVED** [review]

**Pull request merged**
