### PR TITLE
Feature/abstract models

### PR DESCRIPTION
**Pull request by Richard-Mathie**
I had a problem using this with inherited classes. I think you shouldn't sync the abstract class....I forgot to actually set the abstract flag in my test model, which caused the test to fail, this should work now

### CODE REVIEW

**Comment by thegeorgeous** [comment]
@Richard-Mathie, I'm kinda busy, so before I review the PR if you could add a more detailed explanation of the changes, that would be a great help. Plus the tests are failing for all Python versions except 2.7. Could you look into that too?

**Comment by Richard-Mathie** [comment]
We [_"cant create tables from abstract models"_](https://datastax.github.io/python-driver/api/cassandra/cqlengine/models.html#cassandra.cqlengine.models.Model.__abstract__). So if a model is abstract we shouldn't sync that to the database. Also we need to sync all the sub models, or even sub sub models (though probably not). This is useful if you have a particular query pattern, say time series data, you put that pattern, and functions around that in an abstract class, then for different data tables are subclasses of that.

The test example will create two tables cats and dogs, which are based on the pets model. Pets will not be synced to Cassandra.

The code works by recursively iterating through the list of subclasses for a model, if the model is abstract to produce a list of all the non abstract model classes. This should work even if you have abstract models which inherit abstract models.

I have split your test case into a `BaseTestCase` and a `BasicTestCase` so other test cases can inherit the `BaseTestCase`

I have added two functions `flatten` and `get_subclasses`
- `get_subclasses` calls its self on all subclasses of a model if the model is abstract else return its self
- `flatten` flattens an array of arrays into a single array

**Comment by Richard-Mathie** [comment]
any thoughts on this, the tests are passing? Is there anything I can explain better/ improve?

**Comment by thegeorgeous** [comment]
@Richard-Mathie, good catch, would have never noticed this missing. And thanks for the explanation. I'll merge this as soon as I get some free time. Kinda super busy with work.

**Pull request merged**
